theme               = "catppuccin_frappe"
[editor]
line-number         = "relative"
bufferline          = "always"
auto-pairs          = false
[editor.file-picker]
hidden              = false
git-ignore          = false
[editor.soft-wrap]
enable              = true
[editor.lsp]
display-inlay-hints	= true

[keys.normal]
"C-s"               = [ ":write"               ]
"C-r"               = [ "redo"                 ]
"^"                 = [ "goto_line_start"      ]
"$"                 = [ "goto_line_end"        ]
"D"                 = [                         
                        "goto_line_start"      ,
                        "select_mode"          ,          
                        "goto_line_end"        ,        
                        "yank"                 ,                 
                        "normal_mode"          ,          
                        "goto_line_start"      ,      
                        "kill_to_line_end"     ,
                      ]
"d"                 = [  "delete_char_forward" ]
"V"                 = [                         
                        "goto_line_start"      ,      
                        "select_mode"          ,          
                        "goto_line_end"        ,
                      ]
"G"                 = [ "goto_last_line"       ]
"C-c"               = [ "normal_mode"          ]
"Y"                 = [                         
                        "goto_line_start"      ,
                        "select_mode"          ,          
                        "goto_line_end"        ,        
                        "yank"                 ,                 
                        "normal_mode"          ,
                      ]
"C-left"            = [ "jump_view_left"       ]
"C-right"           = [ "jump_view_right"      ]
"C-down"            = [ "jump_view_down"       ]
"C-up"              = [ "jump_view_up"         ]
"C-v"               = [ "vsplit"               ]
"A-v"               = [ "hsplit"               ]
[keys.normal.g]
"q"                 = { q = [                         
                        "goto_line_start"      ,
                        "select_mode"          ,          
                        "goto_line_end"        ,        
                        ":reflow"              ,              
                        "normal_mode"          , 
                      ]}
"^"                 = [ "goto_line_start"      ]
"$"                 = [ "goto_line_end"        ]
[keys.select]
"v"                 = [                         
                        "move_next_word_end"   ,
                        "normal_mode"          ,          
                        "move_prev_word_start" , 
                        "select_mode"          ,          
                        "move_next_word_end"   ,
                      ]
"u"                 = [ "switch_to_lowercase"  ]
"U"                 = [ "switch_to_uppercase"  ]
"^"                 = [ "goto_line_start"      ]
"$"                 = [ "goto_line_end"        ]
"C-s"               = [                         
                        ":write"               ,               
                        "normal_mode"          ,
                      ]
"C-left"            = [ "jump_view_left"       ]
"C-right"           = [ "jump_view_right"      ]
"C-down"            = [ "jump_view_down"       ]
"C-up"              = [ "jump_view_up"         ]
[keys.insert]
"C-s"               = [                         
                        ":write"               ,
                        "normal_mode"          ,
                      ]
"C-left"            = [ "jump_view_left"       ]
"C-right"           = [ "jump_view_right"      ]
"C-down"            = [ "jump_view_down"       ]
"C-up"              = [ "jump_view_up"         ]
