theme               = "nord"
#  ──────────────────────────────────────────────────────────
[editor]
line-number         = "relative"
bufferline          = "always"
auto-pairs          = false
auto-save           = true
completion-replace  = true
true-color          = true
text-width	        = 63
[editor.statusline]
separator           = "│"
mode.normal         = "NORMAL"
mode.insert         = "INSERT"
mode.select         = "SELECT"

left                = [
                        "file-modification-indicator",
                        "mode"                       ,
                        "spinner"                    ,
                      ]
center              = [
                        "position"                   ,
                        "position-percentage"        ,
                        "total-line-numbers"         ,
                        "file-name"                  ,
                        "version-control"            ,
                      ]
right               = [
                        "diagnostics"                ,
                        "selections"                 ,
                        "file-encoding"              ,
                        "file-line-ending"           ,
                        "file-type"                  ,
                      ]
#  ──────────────────────────────────────────────────────────
[editor.whitespace]
render              = "all"
#  ──────────────────────────────────────────────────────────
[editor.indent-guides]
render              = true
#  ──────────────────────────────────────────────────────────
[editor.file-picker]
hidden              = false
git-ignore          = true
#  ──────────────────────────────────────────────────────────
[editor.soft-wrap]
enable              = true
#  ──────────────────────────────────────────────────────────
[editor.lsp]
display-inlay-hints	= true
snippets            = true
display-messages    = true
#  ──────────────────────────────────────────────────────────
[editor.cursor-shape]
normal              = "block"
select              = "underline"
insert              = "bar"
#  ──────────────────────────────────────────────────────────
[keys.normal]
"C-s"               = [ ":write!"                           ]
"A-f"               = [ "file_picker"                       ]
"C-f"               = [ "file_picker_in_current_directory"  ]
"A-b"               = [ "buffer_picker"                     ]
"C-r"               = [ "redo"                              ]
"d"                 = [ "delete_char_forward"               ]
"^"                 = [ "goto_line_start"                   ]
"$"                 = [ "goto_line_end"                     ]
"G"                 = [ "goto_last_line"                    ]
"C-c"               = [ "normal_mode"                       ]
"C-left"            = [ "jump_view_left"                    ]
"C-right"           = [ "jump_view_right"                   ]
"C-down"            = [ "jump_view_down"                    ]
"C-up"              = [ "jump_view_up"                      ]
"C-v"               = [ "vsplit"                            ]
"A-v"               = [ "hsplit"                            ]
"D"                 = [                                      
                        "goto_line_start"                   ,
                        "select_mode"                       ,
                        "goto_line_end"                     ,
                        "yank"                              ,
                        "normal_mode"                       ,
                        "goto_line_start"                   ,
                        "kill_to_line_end"                  ,
                        "delete_char_forward"               ,
                      ]
"V"                 = [                                      
                        "goto_line_start"                   ,
                        "select_mode"                       ,
                        "goto_line_end"                     ,
                      ]
"Y"                 = [                                      
                        "goto_line_start"                   ,
                        "select_mode"                       ,
                        "goto_line_end"                     ,
                        "yank"                              ,
                        "normal_mode"                       ,
                      ]
#  ──────────────────────────────────────────────────────────
[keys.normal.g                                              ]
"^"                 = [ "goto_line_start"                   ]
"$"                 = [ "goto_line_end"                     ]
"q"                 = { q = [                                
                        "goto_line_start"                   ,
                        "select_mode"                       ,
                        "goto_line_end"                     ,
                        ":reflow"                           ,
                        "normal_mode"                       ,
                      ]}
#  ──────────────────────────────────────────────────────────
[keys.select                                                ]
"u"                 = [ "switch_to_lowercase"               ]
"U"                 = [ "switch_to_uppercase"               ]
"^"                 = [ "goto_line_start"                   ]
"$"                 = [ "goto_line_end"                     ]
"C-left"            = [ "jump_view_left"                    ]
"C-right"           = [ "jump_view_right"                   ]
"C-down"            = [ "jump_view_down"                    ]
"C-up"              = [ "jump_view_up"                      ]
"v"                 = [                                      
                        "move_next_word_end"                ,
                        "normal_mode"                       ,
                        "move_prev_word_start" ,             
                        "select_mode"                       ,
                        "move_next_word_end"                ,
                      ] 
"C-s"               = [                                      
                        ":write"                            ,
                        "normal_mode"                       ,
                      ]
#  ──────────────────────────────────────────────────────────
[keys.insert                                                ]
"C-left"            = [ "jump_view_left"                    ]
"C-right"           = [ "jump_view_right"                   ]
"C-down"            = [ "jump_view_down"                    ]
"C-up"              = [ "jump_view_up"                      ]
"C-s"               = [                                      
                        ":write"                            ,
                        "normal_mode"                       ,
                      ]