theme               = "catppuccin_frappe"
#  ──────────────────────────────────────────────────────────
[editor]
line-number         = "relative"
bufferline          = "always"
auto-pairs          = false
auto-save           = true
completion-replace  = true
true-color          = true
#  ──────────────────────────────────────────────────────────
[editor.whitespace]
render              = "all"
#  ──────────────────────────────────────────────────────────
[editor.indent-guides]
render              = true
#  ──────────────────────────────────────────────────────────
[editor.file-picker]
hidden              = false
git-ignore          = false
#  ──────────────────────────────────────────────────────────
[editor.soft-wrap]
enable              = true
#  ──────────────────────────────────────────────────────────
[editor.lsp]
display-inlay-hints	= true
snippets            = true
display-messages    = true
#  ──────────────────────────────────────────────────────────
[editor.cursor-shape]
normal              = "block"
insert              = "underline"
select              = "bar"
#  ──────────────────────────────────────────────────────────
[keys.normal]
"C-s"               = [ ":write"               ]
"C-r"               = [ "redo"                 ]
"d"                 = [ "delete_char_forward"  ]
"^"                 = [ "goto_line_start"      ]
"$"                 = [ "goto_line_end"        ]
"G"                 = [ "goto_last_line"       ]
"C-c"               = [ "normal_mode"          ]
"C-left"            = [ "jump_view_left"       ]
"C-right"           = [ "jump_view_right"      ]
"C-down"            = [ "jump_view_down"       ]
"C-up"              = [ "jump_view_up"         ]
"C-v"               = [ "vsplit"               ]
"A-v"               = [ "hsplit"               ]
"D"                 = [                         
                        "goto_line_start"      ,
                        "select_mode"          ,
                        "goto_line_end"        ,
                        "yank"                 ,
                        "normal_mode"          ,
                        "goto_line_start"      ,
                        "kill_to_line_end"     ,
                        "delete_char_forward"  ,
                      ]
"V"                 = [                         
                        "goto_line_start"      ,
                        "select_mode"          ,
                        "goto_line_end"        ,
                      ]
"Y"                 = [                         
                        "goto_line_start"      ,
                        "select_mode"          ,
                        "goto_line_end"        ,
                        "yank"                 ,
                        "normal_mode"          ,
                      ]
#  ──────────────────────────────────────────────────────────
[keys.normal.g]
"^"                 = [ "goto_line_start"      ]
"$"                 = [ "goto_line_end"        ]
"q"                 = { q = [                  
                        "goto_line_start"      ,
                        "select_mode"          ,
                        "goto_line_end"        ,
                        ":reflow"              ,
                        "normal_mode"          ,
                      ]}
#  ──────────────────────────────────────────────────────────
[keys.select]
"u"                 = [ "switch_to_lowercase"  ]
"U"                 = [ "switch_to_uppercase"  ]
"^"                 = [ "goto_line_start"      ]
"$"                 = [ "goto_line_end"        ]
"C-left"            = [ "jump_view_left"       ]
"C-right"           = [ "jump_view_right"      ]
"C-down"            = [ "jump_view_down"       ]
"C-up"              = [ "jump_view_up"         ]
"v"                 = [                         
                        "move_next_word_end"   ,
                        "normal_mode"          ,
                        "move_prev_word_start" , 
                        "select_mode"          ,
                        "move_next_word_end"   ,
                      ]
"C-s"               = [                         
                        ":write"               ,
                        "normal_mode"          ,
                      ]
#  ──────────────────────────────────────────────────────────
[keys.insert]
"C-left"            = [ "jump_view_left"       ]
"C-right"           = [ "jump_view_right"      ]
"C-down"            = [ "jump_view_down"       ]
"C-up"              = [ "jump_view_up"         ]
"C-s"               = [                         
                        ":write"               ,
                        "normal_mode"          ,
                      ]