import = ["/home/damoon/.config/alacritty/ayu-mirage.toml"]
working_directory = "/home/damoon/sync"

[cursor]
style = "Block"
unfocused_hollow = false

[env]
TERM = "xterm-256color"

# [font.normal]
# family = "Cascadia Code iCursive Cg"

[shell]
args = ["--login"]
program = "/bin/bash"
