---
import:
  - ~/.dotfiles/alacritty/ayu-light.yml
  # - ~/.dotfiles/alacritty/ayu-dark.yml
  # - ~/.dotfiles/alacritty/ayu-mirage.yml
  # - ~/.dotfiles/alacritty/solarized-light.yml
  # - ~/.dotfiles/alacritty/solarized-dark.yml
  # - ~/.dotfiles/alacritty/gruvbox-dark.yml
  # - ~/.dotfiles/alacritty/gruvbox-light.yml
  # - ~/.dotfiles/alacritty/dracula.yml
env:
  TERM: xterm-256color
cursor:
  style: Block
  unfocused_hollow: false
working_directory: "shared-drives/C:/Users/damoon/Sync"