
[cursor]
style = "Block"
unfocused_hollow = false

[env]
TERM = "xterm-256color"

[general]
working_directory = "/home/damoon/sync"
import = ["/home/damoon/.config/alacritty/ayu-mirage.toml"]

[terminal]

# [font.normal]
# family = "Cascadia Code iCursive Cg"

[terminal.shell]
args = ["--login"]
program = "/bin/bash"
