# vim: ft=yaml syntax=yaml softtabstop=2 tabstop=2 shiftwidth=2 fenc=utf-8 expandtab autoindent
---
import:
  # - ~/.config/alacritty/ayu-light.yml
  # - ~/.config/alacritty/ayu-dark.yml
  # - ~/.config/alacritty/ayu-mirage.yml
  # - ~/.config/alacritty/solarized-light.yml
  # - ~/.config/alacritty/solarized-dark.yml
  # - ~/.config/alacritty/gruvbox-dark.yml
  # - ~/.config/alacritty/gruvbox-light.yml
  - ~/.config/alacritty/dracula.yml
env:
  TERM: xterm-256color
cursor:
  style: Block
  unfocused_hollow: false
font:
  normal:
    family: "Cascadia Code iCursive Cg"
working_directory: "/home/damoon/sync"
shell:
  program: /bin/bash
  args:
    - --login
# working_directory: "shared-drives/C:/Users/damoon/Sync"
