#!/usr/bin/env bash
# vim: ft=sh syntax=sh softtabstop=2 tabstop=2 shiftwidth=2 fenc=utf-8 expandtab


# if command -- emplace -h >/dev/null 2>&1; then
#   source <(emplace init bash)
# fi
# [ -x "$(command -v repo)" ] && {
#     [ -x "$(command -v fzf)" ] && eval "$(repo init bash --fzf)" || eval "$(repo init bash)"
# }
# if [ -x "$(command -v zellij)" ] ; then
#   if printenv | grep -Pq 'WINDOW|TERMINAL'; then
#     # [ -d "${HOME}/sync" ] && pushd "${HOME}/sync" > /dev/null 2>&1 ;
#     # export ZELLIJ_AUTO_EXIT="true" ;
#     eval "$(zellij setup --generate-auto-start bash)" ;
#   fi
# fi