name = "Damoon Azarpazhooh"
downloads-dir = "/home/damoon/Downloads"
default-page-size = 50

[protonmail]
default = true
email = "damoon@protonmail.com"

imap-host = "127.0.0.1"
imap-port = 1143
imap-login = "damoon@protonmail.com"
imap-passwd-cmd = "pass show proton"
imap-starttls = true

smtp-host = "127.0.0.1"
smtp-port = 1025
smtp-login = "damoon@protonmail.com"
smtp-passwd-cmd = "pass show proton"
smtp-starttls = true
