display-name = "Damoon Azarpazhooh"
downloads-dir = "~/downloads"
folder-listing-page-size = 50
email-listing-page-size = 50


[protonmail]
default = true
display-name = "Damoon Azarpazhooh"
email = "damoon@protonmail.com"

backend = "imap"
imap-host = "127.0.0.1"
imap-login = "damoon@protonmail.com"
imap-auth = "passwd"
imap-passwd.cmd = "pass show proton"
imap-port = 1143
imap-starttls = true
imap-insecure = true

sender = "smtp"
smtp-host = "127.0.0.1"
smtp-login = "damoon@protonmail.com"
smtp-auth = "passwd"
smtp-passwd.cmd = "pass show proton"
smtp-port = 1025
smtp-starttls = true
smtp-insecure = true

[gmail-personal]

email = "damoon.azarpazhooh@gmail.com"

backend = "imap"
imap-host = "imap.gmail.com"
imap-port = 993
imap-login = "damoon.azarpazhooh@gmail.com"
imap-auth = "passwd"
imap-passwd.cmd = "pass show gmail/personal"

sender = "smtp"
smtp-host = "smtp.gmail.com"
smtp-port = 465
smtp-login = "clement.douin@gmail.com"
smtp-auth = "passwd"
smtp-passwd.cmd = "pass show gmail/personal"
