###############################################################################
#                             Global configuration                             #
###############################################################################

# Display name used by default for all accounts (if not overridden per account).
display-name = "Damoon Azarpazhooh"

# A simple signature, included in all new and reply emails by default.
signature = "Regards,\nDamoon"

# Signature delimiter placed right above the signature content.
signature-delim = "-- \n"

# Default directory for attachments/downloads.
downloads-dir = "~/emails/downloads"


###############################################################################
#                             Gmail account                                   #
###############################################################################
[accounts.gmail]

# Make it the default account if you want all commands to use it by default.
default = true

# Basic identity settings.
email = "damoon.azarpazhooh@gmail.com"
display-name = "Damoon Azarpazhooh"

# Folder (mailbox) aliases – especially important for Gmail, where Sent Mail, Drafts, etc.
folder.aliases.inbox  = "INBOX"
folder.aliases.sent   = "[Gmail]/Sent Mail"
folder.aliases.drafts = "[Gmail]/Drafts"
folder.aliases.trash  = "[Gmail]/Trash"

# --- IMAP settings ---
backend.type                  = "imap"
backend.host                  = "imap.gmail.com"
backend.port                  = 993
backend.encryption.type       = "tls"
backend.login                 = "damoon.azarpazhooh@gmail.com"
backend.auth.type             = "password"
backend.auth.cmd              = "pass show gmail/personal"

# --- SMTP settings ---
message.send.backend.type            = "smtp"
message.send.backend.host            = "smtp.gmail.com"
message.send.backend.port            = 465
message.send.backend.encryption.type = "tls"
message.send.backend.login           = "damoon.azarpazhooh@gmail.com"
message.send.backend.auth.type       = "password"
message.send.backend.auth.cmd        = "pass show gmail/personal"

# Increase folder and message listing page sizes 
folder.list.page-size = 50
envelope.list.page-size = 50

# Let's also enable a few nice extras from the sample config:

# Always store a copy of sent messages in the "sent" folder (Gmail's [Gmail]/Sent Mail).
message.send.save-copy = true

envelope.list.datetime-fmt = "%F %R%:z"
envelope.list.datetime-local-tz = true
folder.list.table.preset = "||  |-|||           "
folder.list.table.name-color = "blue"
folder.list.table.desc-color = "green"
envelope.list.table.preset = "||  |-|||           "
envelope.list.table.id-color = "red"
envelope.list.table.flags-color = "black"
envelope.list.table.subject-color = "green"
envelope.list.table.sender-color = "blue"
envelope.list.table.date-color = "yellow"
